# Generated by Django 5.1.4 on 2025-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0002_lottoticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sales_open', models.BooleanField(default=True)),
            ],
        ),
    ]
